### ISSUE TITLE
Using Swift WebGPU

### ISSUE THREAD

**Issue by stackotter** [henrybetts/swift-webgpu#1]
Hi Henry,

This project looks great and I'd love to use it in [my project](https://github.com/stackotter/delta-client) (the screenshots in my readme are outdated, but the ones on [the website](https://delta.stackotter.dev) mostly aren't).

Currently my project uses Metal and is constrained to macOS but I'm planning on moving away from Metal to support Linux and Windows.

Is there somewhere (such as Discord) that I can contact you? If I start using Swift WebGPU I'll probably help out with development and it'd be good to be in contact. My email is stackotter@stackotter.dev and my Discord is stackotter#3100 (just in case you don't feel comfortable sharing any contact details on GitHub).

I look forward to chatting further :)

**Comment by henrybetts** [comment]
Thanks!

I hope that WebGPU does become a viable option for native development in the future. It has a nice API (fairly similar to metal in terms of complexity I believe) and is backed by a standard.

It is still early days though and the upstream spec is probably not stable yet, though is getting close to a v1 API I think.

Probably best to email me at henry@henrybetts.co.uk

**Comment by stackotter** [comment]
Yeah, when I was looking at the spec there are a lot of similarities with metal. I'm happy to work with an unstable api, but first i need to figure out how to get it building properly hahah
