### ISSUE TITLE
Building Errors

### ISSUE THREAD

**Issue by AryzenRS** [henrybetts/swift-webgpu#10]
I have attached the output of my attempt to build, probably a mistake on my end. Likeliest issue is my dawn.json is not in the correct place or is malformed. The errors seem to originate from "GenerateWebGPUPlugin". 

[error.txt](https://github.com/user-attachments/files/17534917/error.txt)

**Comment by henrybetts** [comment]
Ah there's probably been a breaking change in the upstream dawn.json. I'll take a look.

**Comment by henrybetts** [comment]
Can you try again with the latest @AryzenRS ?

**Comment by AryzenRS** [comment]
It builds successfully, I assume it works correctly! Thanks for the swift (heh) fix!
